language: php

php:
  - 5.4

services: 
  - mongodb

before_script: 
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - phpenv config-add travis_config.ini
  - composer install -n
  - mysql -e 'create database netid_test;'
  - mongo netid_log_test
  - php app/console cache:clear --env=prod
  - php app/console assets:install --env=prod
  - php app/console assetic:dump --env=prod
  - php app/console doctrine:schema:update --force

script: phpunit -c app