fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin/

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

users:
    path:     /api/users/
    defaults: { _controller: PdRNetIdBundle:User:index }

users_insert:
    path:     /api/users/new
    defaults: { _controller: PdRNetIdBundle:User:insert }
    methods: [POST]

users_verbs:
    path:     /api/allowed/
    defaults: { _controller: PdRNetIdBundle:User:allowed }
    methods: [POST]

root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true