democracy_os_net_id_api:
    resource: "@DemocracyOSNetIdApiBundle/Resources/config/routing.yml"
    prefix:   /

democracy_os_net_id_admin:
    resource: "@DemocracyOSNetIdAdminBundle/Resources/config/routing.yml"
    prefix:   /

sonata_admin_routing:
    resource: sonata_admin_routing.yml

sonata_user_routing:
    resource: sonata_user_routing.yml

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_redirect
        permanent: true