security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users: [{ name: %admin.username%, password: %admin.password%, roles: 'ROLE_PDR' }]

    role_hierarchy:
        ROLE_READER:
            - ROLE_SONATA_ADMIN_USER_LIST
            - ROLE_SONATA_ADMIN_USER_VIEW
            - ROLE_SONATA_ADMIN_USERSCLIENTS_LIST
            - ROLE_SONATA_ADMIN_USERSCLIENTS_VIEW
        ROLE_ADMIN:
            - ROLE_SONATA_ADMIN_USER_EDIT
            - ROLE_SONATA_ADMIN_USER_CREATE
            - ROLE_SONATA_ADMIN_USERSCLIENTS_EDIT
            - ROLE_SONATA_ADMIN_USERSCLIENTS_CREATE
            - ROLE_SONATA_ADMIN_USERSCLIENTS_DELETE
        ROLE_SUPER_ADMIN:
            - ROLE_SONATA_ADMIN_USER_DELETE
            - ROLE_SONATA_ADMIN_USER_EXPORT
        ROLE_STAFF: [ROLE_READER]
    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        admin:
            pattern: ^/admin/login/
            http_basic: true
            provider: in_memory

        main:
            pattern: ^/admin/
            anonymous: ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
                login_path:  /admin/login/
                check_path:  /admin/login_check/
            logout:
                path:    /admin/logout/
                target:  /admin/login/
                invalidate_session: false

    access_control:
        - { path: ^/admin/login/, role: ROLE_PDR }
        - { path: ^/admin/, role: [ROLE_STAFF, ROLE_ADMIN, ROLE_SUPER_ADMIN] }