security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/users
            fos_oauth:  true
            stateless:  true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
            logout:
                path:    /logout
                target:  /login
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/(_(profiler|wdt)|css|images|js|bundles)/, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }