security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        client_applications:
            entity: { class: PdR\NetIdBundle\Entity\ClientApplication, property: description }

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/users
            fos_oauth:  true
            stateless:  true

    access_control:
        - { path: ^/users, roles: [ IS_AUTHENTICATED_FULLY ] }