services:
    sonata.admin.user:
        class: PdR\NetIdBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - PdR\NetIdBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [PdRNetIdBundle]]
            - [ setEntityManager, [@doctrine.orm.entity_manager]]

    sonata.admin.usersclients:
        class: PdR\NetIdBundle\Admin\UsersClientsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User clients", show_in_dashboard: false }
        arguments:
            - ~
            - PdR\NetIdBundle\Entity\UsersClients
            - ~

    sonata.admin.client:
        class: PdR\NetIdBundle\Admin\ClientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Clients", show_in_dashboard: false }
        arguments:
            - ~
            - PdR\NetIdBundle\Entity\Client
            - ~

    sonata.admin.role:
        class: PdR\NetIdBundle\Admin\RoleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Administration", label: "Role", show_in_dashboard: true }
        arguments:
            - ~
            - PdR\NetIdBundle\Entity\Role
            - ~
            - ~

    sonata.admin.action:
        class: PdR\NetIdBundle\Admin\ActionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Administration", label: "Action", show_in_dashboard: true }
        arguments:
            - ~
            - PdR\NetIdBundle\Entity\Action
            - ~

    sonata.admin.action:
        class: PdR\NetIdBundle\Admin\ActionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Log", label: "User log", show_in_dashboard: true }
        arguments:
            - ~
            - PdR\NetIdBundle\Entity\UserLog
            - ~