services:
    sonata.admin.identity:
        class: DemocracyOS\NetIdAdminBundle\Admin\IdentityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Identity" }
        arguments:
            - ~
            - DemocracyOS\NetIdAdminBundle\Entity\Identity
            - ~
    sonata.admin.application:
        class: DemocracyOS\NetIdAdminBundle\Admin\ApplicationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Application" }
        arguments:
            - ~
            - DemocracyOS\NetIdApiBundle\Entity\Application
            - ~